branches:
    only:
        - master

sudo: required

language: php

php:
    - '7.0'
    - '7.1'
    - '7.2'

before_script:
  - cd src
  - composer self-update

install:
    - cd src
    - composer install

notifications:
    on_success: never
    on_failure: always
