name: CI Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Run composer install
      working-directory: src
      run: |
        composer install --prefer-dist
